In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
my_mat=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
my_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.70386674, 0.08759432, 0.97357514, 0.0338229 , 0.38486404])

In [21]:
np.random.rand(5,5)

array([[0.46288329, 0.31506077, 0.83970781, 0.84833974, 0.90290233],
       [0.40942022, 0.72184158, 0.47792218, 0.80489651, 0.15166101],
       [0.60283848, 0.20988778, 0.10613279, 0.10880433, 0.31020349],
       [0.66820205, 0.472532  , 0.0074646 , 0.19332523, 0.87429245],
       [0.7168707 , 0.24300456, 0.06876775, 0.20533946, 0.81579624]])

In [22]:
np.random.randn(5)

array([ 1.05211479, -0.59394314, -1.22329654, -0.81752189, -0.1310912 ])

In [23]:
np.random.randn(4,4)

array([[ 0.76514345,  1.29801552,  0.64603063,  1.0280331 ],
       [ 0.58522425, -0.50874226,  0.62972696,  0.28846065],
       [ 0.40263005,  1.63976636,  0.97090067,  0.83342912],
       [ 1.0611115 ,  0.94151434, -0.71363949,  0.69287268]])

In [24]:
np.random.randint(1,10,5)

array([3, 7, 1, 4, 3])

In [25]:
ranarr=np.random.randint(0,50,10)

In [26]:
ranarr

array([33,  8, 21, 13, 34,  3, 21, 14, 45,  0])

In [27]:
ranarr.reshape(2,5)

array([[33,  8, 21, 13, 34],
       [ 3, 21, 14, 45,  0]])

In [28]:
ranarr.max()

45

In [29]:
ranarr.min()

0

In [30]:
ranarr.argmax()

8

In [31]:
ranarr.argmin()

9

In [33]:
ranarr.shape

(10,)

In [35]:
ranarr.dtype

dtype('int32')

In [40]:
from numpy.random import randint
from numpy.random import randn
from numpy.random import rand

In [41]:
randint(1,10,5)

array([5, 3, 6, 7, 3])

In [42]:
randn(6)

array([-0.33289392, -0.67284439, -0.83991537, -2.63333071,  1.03830879,
       -1.74576675])

In [43]:
rand(6)

array([1.35653803e-01, 4.45725867e-01, 9.81957249e-01, 1.17827125e-01,
       8.50091089e-04, 9.76865720e-01])